var price=345;
var rating=4.5;
var brand_name='louis philippi';
var prod_name="mens casual shirt";
var availability='N';
var location;
var discount=true;
console.log(price);
console.log(typeof price);
console.log(rating);
console.log(typeof rating);
console.log(brand_name);
console.log(typeof brand_name);
console.log(prod_name);
console.log(typeof prod_name);
console.log(availability);
console.log(typeof availability);
console.log(discount);
console.log(typeof discount);
console.log(location);
console.log(typeof location);